<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <?= $this->tag->getTitle() ?>
        <?= $this->tag->stylesheetLink('/css/bootstrap.min.css') ?>
        <?= $this->tag->stylesheetLink('/css/dashboard.css') ?>
    </head>
    <body>
        <div class="container">
            <h1>Not found :(</h1>
            <em>This page is located in views/404.phtml</em>
        </div>
    </body>
</html>
