<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <?= $this->tag->getTitle() ?>
        <?= $this->tag->stylesheetLink('/css/bootstrap.min.css') ?>
        <?= $this->tag->stylesheetLink('/css/dashboard.css') ?>
    </head>
    <body>
        <div class="container">

            <div class="page-header">
                <h1>Congratulations!</h1>
            </div>

            <p>You're now flying with Phalcon. Great things are about to happen!</p>

            <p>This page is located at <code>views/index.phtml</code></p>
        </div>
        <!-- jQuery first, then Popper.js, and then Bootstrap's JavaScript -->
        <?= $this->tag->javascriptInclude('/js/bootstrap.min.js') ?>
        <?= $this->tag->javascriptInclude('/js/dashboard.js') ?>
        <?= $this->tag->javascriptInclude('/js/jquery.min.js') ?>
        <?= $this->tag->javascriptInclude('/js/utils.js') ?>
    </body>
</html>
